version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    env_file:
      - ./.env
    environment:
      MYSQL_DATABASE: picpay-backend
      MYSQL_USERNAME: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - '3007:3306'
    expose:
      - '3007'
